### ISSUE TITLE
AssertionError: features.shape[1] % nElectrodes == 0

### ISSUE THREAD

**Issue by WolfgangGross** [pouya-bashivan/EEGLearn#1]
When I run the *\* eeg_cnn_lib.py *\* script. This AssertionError Pops Up:
AssertionError: features.shape[1] % nElectrodes == 0

With:
features.shape[1] -> 31
nElectrodes -> 10

As far as I understand from the comments in the Code the shape of features is [n_saples, n_features + 1].

So a fix in **gen_images** [line: 41] could be:
    n_features  = features.shape[1] - 1

```
# Test whether the feature vector length is divisible by number of electrodes (last column is the labels)
assert n_features % nElectrodes == 0
n_colors = n_features / nElectrodes
```

Is my understanding correct?

**Comment by pbashivan** [comment]
@WolfgangGross ,
Thanks for raising the issue!
I recently changed the code so the input to gen_images would be the feature matrix without the labels column but forgot to change the test code. 
Try feeding only your feature matrix [n_samples, n_features] to gen_images function when you call it.
