### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by ShibaPrasad** [pouya-bashivan/EEGLearn#10]
Thank you for your [previous replies](https://github.com/pbashivan/EEGLearn/issues/8). I read your paper and also understand the procedure. Able to run your program end to end. But not able to figure out how to generate those data files - if i am using different data sets.

Sample data folder location:
https://github.com/pbashivan/EEGLearn/tree/master/Sample%20data 

But i would like to know how the below files formed (As i am trying with different data sets)

FeatureMat_timeWin.mat
Neuroscan_locs_orig.mat
trials_subNums.mat

**Comment by pbashivan** [comment]
trials_subNums: contains subject number ids for each trial, basically which subject the trial belongs to

Neuroscan_locs_orig: 3D locations for each electrode you are using. Most caps are based on standard 10-10 electrodes that you can find their coordinates from 'python mne' or EEGLAB

FeatureMat_timeWin: It is described in the paper. Basically for each trial and electrode, apply FFT on the time binned data and average the power over the frequency bands of interest.

**Comment by ShibaPrasad** [comment]
Thank you. It's much clear now. Working on it ..........

**Comment by pbashivan** [comment]
Great! Closing this...
