### ISSUE TITLE
dimention of FeatureMat_timeWin.mat

### ISSUE THREAD

**Issue by anindyasarkarIITH** [pouya-bashivan/EEGLearn#12]
this file (FeatureMat_timeWin.mat) has shape (2670,1345). 2670 is the number of subjects. but from where 1345 is coming?the last column (i.e. 1345th one is for classification levels)but how you are getting the number 1344?
what I understand is that for each EEG signal (ONE OF 64 EEG SIGNAL) I have to take FFT and then get the spectral power for each of the three frequency band.So I will be getting 3 different values for three different frequency bands.So, ultimately I will be getting 64 values for one subject trial and for one frequency band.
please correct me If my understanding is wrong?and I want to know how you are getting that feature matrix with the number of column 1345?

**Comment by anindyasarkarIITH** [comment]
1344 is (64 * 21)..the first (64 * 3) values will be for (theta_1, theta_2..., theta_64, alpha_1, alpha_2, ..., beta_64)..and likewise there are 7 time windows and each contains (64 * 3) values.and we concatenate all these values for a subject in column wise...so (64 * 3) * 7 =1344 ... is coming..

Is it correct?please correct me if I am wrong..

**Comment by pbashivan** [comment]
You got it right. There are 3 freq bands, 64 electrodes, and 7 time windows. Sequence of columns is theta power (all electrodes, time window-1), alpha power (all electrodes, time window-1), gamma power (all electrodes, time window-1), theta power (all electrodes, time window-2), and so on.
I tried to explain this here:
https://github.com/pbashivan/EEGLearn/blob/master/Sample%20data/README.txt

**Comment by ShibaPrasad** [comment]
Hi pbashivan
I believe - you have considered "peek value of power spectrum"  (for each - theta, alpha, beta spectrum) as features (i.e 1344 features).  Please clarify if i am wrong.

How one will calculate those on a given online/public EEG data sets?
How one will find the last column i.e 1345th column? (for online EEG data sets)

Shiba

**Comment by pbashivan** [comment]
@ShibaPrasad 
I used the average power within each frequency band of interest. I think this would be a better estimate of the shape of PSD. Taking the max might be noisy. 
1. You can divide the time series into windows and apply FFT on each window or use wavelet transformation on the complete signal and then divide it to windows. 
2. The last column (1345th) contains the target labels which any dataset would have one of its own.

**Comment by ShibaPrasad** [comment]
Thanks pbashivan. Can I use EEGLAB for above 1) and 2) part (as explained on your last reply) 
or 
You will recommend any other tools for above specific task

**Comment by pbashivan** [comment]
EEGLAB is a fine tool for this.
