### ISSUE TITLE
Classification Results for each fold

### ISSUE THREAD

**Issue by ShibaPrasad** [pouya-bashivan/EEGLearn#13]
Hi pbashivan,
How to calculate the Table – 4 i.e. classification results for each subjects? Please give me some hints. Which module does this job(On your program eeg_cnn_lib.py)?

**Comment by pbashivan** [comment]
Table 4 is the classification results over each subject. You train on all but one subject and test it on the held-out subject. I don't think I have put it in the code but it should be simple to implement.

**Comment by ShibaPrasad** [comment]
Thank you
Just thinking to clarify one more question: 
How you are calculating Test Error from you “eeg_cnn_lib.py” output (Table -2)? I believe …….doing something wrong on my experiment. Want to clarify.

**Comment by ShibaPrasad** [comment]
I removed my previous question and it was based on those table-2 error rate. Let me try once more.

**Comment by pbashivan** [comment]
I'm closing this, feel free to reopen.
