### ISSUE TITLE
Average power within each frequency band of interest

### ISSUE THREAD

**Issue by ShibaPrasad** [pouya-bashivan/EEGLearn#14]
Hi 
I am not able to figure out the below stuff on EEGLAB tool. would you please help on this....I am totally stuck on my experiment and using online data sets

from your previous reply: 
at URL - https://github.com/pbashivan/EEGLearn/issues/12 
i was advised below stuffs to calculate.
__________________________________________________
I used the average power within each frequency band of interest. I think this would be a better estimate of the shape of PSD. Taking the max might be noisy.

You can divide the time series into windows and apply FFT on each window or use wavelet transformation on the complete signal and then divide it to windows.

Please help me on this.

**Comment by pbashivan** [comment]
You can use matlab’s [FFT](https://www.mathworks.com/help/matlab/ref/fft.html) function. It will give you range of frequencies and power values for each. In python you can use this [function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fft.html#numpy.fft.fft) which is comparable to matlab’s version.
