### ISSUE TITLE
electrodes 10-20 problem

### ISSUE THREAD

**Issue by qinqian** [pouya-bashivan/EEGLearn#16]
Hi, 

It's lucky to known the nice package. We have encountered a problem by matching the FFT signal with elect, electrodes position from 10-20 coordinates for newborn. 

We used 4 electrodes here since the baby's brain surface is not big enough. The bi-channel (e.g c3-c4,p3-p4) signal is measured by comparing two electrodes for theta, alpha and beta. 

Can we use the coordinates centre for C3 and P3 for 29th line here? Or is there a way to adopt your models?

Thanks,
Best

**Comment by pbashivan** [comment]
Images are more meaningful when you have a common reference electrode or using average reference. In that case every electrode becomes a point in the space. However using bipolar electrodes, it becomes less clear how to interpret the images cause now each bipolar value is a difference voltage with respect to a different reference point. 
I can think of two ways:
1. re-reference your data to 'average reference' and use the standard 10-20 locations.
2. use bipolar signals and for the location use the middle point between the two electrode locations. (not the best way but you can try)

**Comment by qinqian** [comment]
We will try the 2nd suggestion first. Thanks so much for the suggestion.
