### ISSUE TITLE
a question about Sample Data

### ISSUE THREAD

**Issue by wuguowei1994** [pouya-bashivan/EEGLearn#18]
what is the sense of 1345th columns in Sample data/FeatureMat_timeWin.mat? I read the whole code,and i find this columns is not used.In my view, the label is recorded in trials_subNums.mat, right?

**Comment by pbashivan** [comment]
the last column (1345th) contains the labels.

**Comment by wuguowei1994** [comment]
But what the recorded in trials_subNums.mat used for?
