### ISSUE TITLE
I use your code on my EEG data,But the accuracy is 32%,can you help me?

### ISSUE THREAD

**Issue by wuguowei1994** [pouya-bashivan/EEGLearn#20]
I write a blog,and upload my brain data on internet,you can download my data on my blog.
It's 64 electrodes.
blog link : http://wuguowei.com/wordpress/archives/1592
EEG data link : http://wuguowei.com/nextcloud/index.php/s/ZTsym242i4ZZrvn

**Comment by wuhualu185086661** [comment]
four motor imagery
left hand,right hand,double legs, rest

**Comment by pbashivan** [comment]
Several questions:
1. Have you tried any simple models like SVC to see what the baseline accuracy is?
2. How are you preprocessing your data? Are you standardizing it? I'm assuming you are extracting the power features from relevant frequency bands. 
3. Have you looked at the generated images to see if they look correct?

**Comment by wuhualu185086661** [comment]
could you give me your source code for dealing with original brain data to eeglearn data?
how to deal with the original brain data?

**Comment by SuyuanLiu** [comment]
Would you please tell where to find the 3D coordinates of the 64 electrodes(10-20)? I have been confused for days.
