### ISSUE TITLE
float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Twinkle123321** [pouya-bashivan/EEGLearn#21]
Hi,when I run the code,it shows as following:
Loading data...
Generating images...
Traceback (most recent call last):
  File "C:/Users/Guo/Desktop/EEGLearn-master/eeglearn/eeg_cnn_lib.py", line 473, in <module>
    av_feats = reduce(lambda x, y: x+y, [feats[:, i*192:(i+1)*192] for i in range(feats.shape[1] / 192)])
TypeError: 'float' object cannot be interpreted as an integer

so I modify the part of line 473 as" (feats.shape[1] //192)" ,it shows:
Loading data...
Generating images...
Traceback (most recent call last):
  File "C:/Users/Guo/Desktop/EEGLearn-master/eeglearn/eeg_cnn_lib.py", line 477, in <module>
    32, normalize=False)
  File "C:/Users/Guo/Desktop/EEGLearn-master/eeglearn/eeg_cnn_lib.py", line 67, in gen_images
    for c in range(n_colors):
TypeError: 'float' object cannot be interpreted as an integer

would you give me some suggestions?thank you

**Comment by pbashivan** [comment]
What data are you trying to load? Is it the sample_data or another dataset?

**Comment by Twinkle123321** [comment]
wow,thank you to answer my question,I'm trying to load the sample_data
should code  be supported by GPU?

**Comment by pbashivan** [comment]
Code should be runnable on GPU. 
I can't recreated the error on my end. What's the shape of `feats`?

**Comment by Twinkle123321** [comment]
sorry，when I update the version of Keras,it could run successful,thank you!
I want to ask another very simple math question of code:
def azim_proj(pos):
    [r, elev, az] = cart2sph(pos[0], pos[1], pos[2])
    return pol2cart(az, m.pi / 2 - elev)
function pol2cart(theta,rho) 's second param should be radius,but "m.pi / 2 - elev" is a angle,how it works?

**Comment by pbashivan** [comment]
We actually ignore `r` because we assume that all points are located on a sphere. Azimuthal equidistance projection keeps retains the distance between points on the sphere to a fixed point (e.g. north pole on earth map) while projecting down to 2D. So pi/2 - elevation is the true measure of distance between the fixed point and every other point. This is the conceptual reason why `pi/2 - elevation` is used as `r`. Some math related to this is discussed in [here](https://en.wikipedia.org/wiki/Azimuthal_equidistant_projection)

**Comment by Twinkle123321** [comment]
OK，thank you very much

**Comment by wangyue663** [comment]
Because the author uses 2.7 python and you use 3.5 python, you have to change'\' to'\\'

**Comment by wangyue663** [comment]
Because the author uses 2.7 python and you use 3.5 python, you have to change'\' to'\\'

**Comment by wangyue663** [comment]
Because the author uses 2.7 python and you use 3.5 python, you have to change'\' to'\\'
