### ISSUE TITLE
Can I use your code to classify of EEG motor imagery signals?

### ISSUE THREAD

**Issue by wuguowei1994** [pouya-bashivan/EEGLearn#24]
Your experiment is based on known and unknown the words , If I want to classify motor imagery , how can I do it?

**Comment by pbashivan** [comment]
You should be able to do so by following these steps: 
1. Find the electrode coordinates (x, y, z) and use function [azim_proj](https://github.com/pbashivan/EEGLearn/blob/master/eeglearn/eeg_cnn_lib.py#L25-L37) to project them to 2D. 

2. Use function [gen_images](https://github.com/pbashivan/EEGLearn/blob/master/eeglearn/eeg_cnn_lib.py#L40-L104) to transform your EEG feature matrix and electrode locations into multi-channel images. 

3. Train a CNN or R-CNN to classify each action category given the images or sequence of images. You can use the sample code [here](https://github.com/pbashivan/EEGLearn/blob/master/eeglearn/eeg_cnn_lib.py#L447-L494).

**Comment by pbashivan** [comment]
Feel free to open if there are more related issues.
