### ISSUE TITLE
How to transfer EEG signals to features maps?

### ISSUE THREAD

**Issue by dalvlv** [pouya-bashivan/EEGLearn#25]
I don't know that How to transfer original EEG signals in time series to Spectral Topography Maps? Can you offer a toolkit to achieve that ?

**Comment by pbashivan** [comment]
I have used [EEGLAB](https://sccn.ucsd.edu/eeglab/index.php) in matlab and [mne](https://github.com/mne-tools/mne-python) in python. 
Also see #24 for steps to generate images once you have all spectral features.

**Comment by dalvlv** [comment]
OK，got it. Thank you very much!
