### ISSUE TITLE
Error in "Starting Training session'

### ISSUE THREAD

**Issue by CatramboneVincenzo** [pouya-bashivan/EEGLearn#28]
Hi everyone,
very interesting work. I am trying to use it with my dataset. I create the features matrix just like your, but in my case it is [2696 1603] ( I have 2696 example of 3 classes, 89 channels, 3 frequency bands and 6 time windows). I got the following error and I don't know how to fix it. Can anyone help me please?
Thanks a lot

> ValueError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    902             outputs =\
--> 903                 self.fn() if output_subset is None else\
    904                 self.fn(output_subset=output_subset)

ValueError: y_i value out of bounds

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-22-ccc0d59a02d1> in <module>()
      1 # Class labels should start from 0
      2 print('Training the CNN Model...')
----> 3 train(images, np.squeeze(feats[:, -1]) - 1, fold_pairs[2], 'cnn')

<ipython-input-1-5cf31ca2aaec> in train(images, labels, fold, model_type, batch_size, num_epochs)
    398         for batch in iterate_minibatches(X_train, y_train, batch_size, shuffle=False):
    399             inputs, targets = batch
--> 400             train_err += train_fn(inputs, targets)
    401             train_batches += 1
    402         # And a full pass over the validation data:

~\Anaconda3\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    915                     node=self.fn.nodes[self.fn.position_of_error],
    916                     thunk=thunk,
--> 917                     storage_map=getattr(self.fn, 'storage_map', None))
    918             else:
    919                 # old-style linkers raise their own exceptions

~\Anaconda3\lib\site-packages\theano\gof\link.py in raise_with_op(node, thunk, exc_info, storage_map)
    323         # extra long error message in that case.
    324         pass
--> 325     reraise(exc_type, exc_value, exc_trace)
    326 
    327 

~\Anaconda3\lib\site-packages\six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

~\Anaconda3\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    901         try:
    902             outputs =\
--> 903                 self.fn() if output_subset is None else\
    904                 self.fn(output_subset=output_subset)
    905         except Exception:

ValueError: y_i value out of bounds
Apply node that caused the error: CrossentropySoftmaxArgmax1HotWithBias(Dot22.0, b, targets)
Toposort index: 106
Inputs types: [TensorType(float64, matrix), TensorType(float64, vector), TensorType(int32, vector)]
Inputs shapes: [(32, 3), (3,), (32,)]
Inputs strides: [(24, 8), (8,), (4,)]
Inputs values: ['not shown', array([0., 0., 0.]), 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(CrossentropySoftmaxArgmax1HotWithBias.0)], [CrossentropySoftmax1HotWithBiasDx(Elemwise{Inv}[(0, 0)].0, CrossentropySoftmaxArgmax1HotWithBias.1, targets)], []]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by pbashivan** [comment]
What are your class label values? They should start from 0.

**Comment by pbashivan** [comment]
Feel free to reopen if the issue still persists
