### ISSUE TITLE
Performance on ECG(Electrocardiograph)?

### ISSUE THREAD

**Issue by wenruij** [pouya-bashivan/EEGLearn#3]
Hi Pouya,
  Just curious, have you ever tried on ECG data? like [Physionet's PTBDB](https://physionet.org/physiobank/database/ptbdb/), which contains 16 channels

 Ii's a creative idea to use RCNN on time series, which has been converted into sequence of frames

**Comment by pbashivan** [comment]
Hi @wenruij 
You are right about using the same idea on multi-channel time series - we also thought about this in the beginning. We haven't tried it on anything other than EEG yet. It sounds like a very interesting extension but unfortunately everybody has limited time. I will try to look at the dataset. Let me know if you are interested to collaborate on this.

**Comment by wenruij** [comment]
Hi @pbashivan 
  I’m planning to work on the PTBDB disease classification in the coming few days(I Just finished some working on beat classification of MIT-BIH Arrhythmia DB). It is a pleasure to work with you.  We can schedule this if you get free time.

**Comment by pbashivan** [comment]
@wenruij  
Sound good! Can you send me an email to bashivan[[at]]mit.edu

**Comment by ShibaPrasad** [comment]
Hi wenruji 
Have to tried the code for Physionet's PTBDB ?
