### ISSUE TITLE
Some questions about imshow

### ISSUE THREAD

**Issue by kirby3345678** [pouya-bashivan/EEGLearn#30]
@pbashivan Dear prof, I'm a student from Taiwan, I've some question want to ask you:    

 I've same error like[#27](https://github.com/pbashivan/EEGLearn/issues/27), so I fix eeg_cnn_lib.py  that can run and train in python 3.5.4 . When it done, I've weights_lasg_cnn.npz and weights_lasg_mix.npz file, but I can't see any images even I use matplotlib to plot. 
After I check error msg  it said: Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

I want to know how to solve these problem, I am looking forward to your feedback at your earliest convenience.
Thank you

**Comment by pbashivan** [comment]
You should NOT clip the data. Try rescaling your data to match the value range you mentioned. [0-1] for float or [0-255] for uint8

**Comment by pbashivan** [comment]
Feel free to reopen.
