### ISSUE TITLE
What form of data should be given?

### ISSUE THREAD

**Issue by ta-seri** [pouya-bashivan/EEGLearn#35]
Hi
I would like to generate EEG images using other data (DEAP dataset).
But, I have parts that I can not understand in your code.

 images = eeglib.gen_images(np.array(locs_2d), features, nGridPoints)

I saw "eeg_cnn_lib.py", but I couldn't understand "features" given as a features.
What form of data should be given?

**Comment by pbashivan** [comment]
Have your features in the following format first: `[n_samples, n_bands, n_electrodes]`, where n_samples is "the number of samples", n_bands is "number of feature categories e.g. number of frequency bands", and n_electrodes is "number of electrodes" you have. 
Then reshape your features to have the shape `[n_samples, n_features]`, for instance by running `np.reshape(feats, newshape=[n_samples, -1])`

**Comment by ta-seri** [comment]
I was able to run the program in the way you taught me. Thank you very much!

**Comment by haojiubujian91** [comment]
Hello, I am also working on the Deap dataset, how is the result of your emotion classification using this method?
