### ISSUE TITLE
Problem plotting images

### ISSUE THREAD

**Issue by IsaacSpace** [pouya-bashivan/EEGLearn#36]
Dear Professor:

I've been working with your library and I've got a problem. Here's the error: 

> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

How can I rescale to 0-255 interval? 

Greetings

**Comment by pbashivan** [comment]
If you know what the range of your values are then simply map them to 0-255 range by centering and rescaling. e.g. if your values are in -1 to 1 range then add +1 and multiply by 127.5 and convert to uint8.

**Comment by IsaacSpace** [comment]
Thanks for your answer. I'm analyzing the data (sample data) from your repository and the values after gen_images aren't between -1 and 1. I'm normalizing with feature scaling (between 0 and 255 values) and then I convert the image to uint8.

I'm getting this image:


![figure_1](https://user-images.githubusercontent.com/30877369/53932844-f8fada80-4058-11e9-81b4-5f47c2dcc2f0.png)

I don't know if it is right or wrong... I'm working with your eeg_cnn_lib.py file, just familiarizing myself with your code.

Sincerely, thanks for your response.

Isaac

**Comment by wangyue663** [comment]
Hello, can you tell me what library and function are used to generate the two-dimensional image of brain waves, thanks
