### ISSUE TITLE
the average power value in the FeatureMat_time

### ISSUE THREAD

**Issue by sdnuzwk** [pouya-bashivan/EEGLearn#37]
Dear Professor, how is the average power value in the FeatureMat_timeWin file calculated?
I am in a puzzle

**Comment by pbashivan** [comment]
As was described in the paper: For each electrode, we performed FFT on each 1-sec time window and averaged the power values within different frequency bands.

**Comment by sdnuzwk** [comment]
Since it is an energy value, why is it less than 0?

**Comment by pbashivan** [comment]
These are standardized power values. Each column is centered and scaled to have std=1
