### ISSUE TITLE
Python module version? What are the versions of each module that you used?

### ISSUE THREAD

**Issue by Ibrainscn** [pouya-bashivan/EEGLearn#38]
File "C:\Users\myUser\AppData\Local\Continuum\anaconda2\lib\site-packages\lasagne\__init__.py", line 17, in <module>
    from . import nonlinearities

ImportError: cannot import name nonlinearities

I am wonder are there any other specific requirements to run your code(e.g. specific modules version, python environment)? Can you kindly write a demo to show how to run your code? I really want to try out your method on my EEG data. Really appreciate!

**Comment by pbashivan** [comment]
From the looks of it the error is caused by lasagne and probably due to differences in versions. 

The code was tested with the following: 

```
python 2.7 
theano 0.8 
lasagne 0.2.dev1 
CUDA 8.0
```
I updated the setup file to included these.

**Comment by Ibrainscn** [comment]
Thanks a lot! I tried with exactly the above version. 
It can run Loading data...
Generating images...
Interpolating 2594/2670Interpolating 2611/2670Interpolating 2630/2670Interpolating 2648/2670Interpolating 2665/2670

Training the CNN Model...
fold 1/13
Traceback (most recent call last):
**And then give me the following error:**

  File "C:\Users\myUser\AppData\Local\Continuum\anaconda2\lib\site-packages\theano\tensor\type.py", line 47, in __init__
    # broadcastable is immutable, and all elements are either

AttributeError: 'TheanoConfigParser' object has no attribute 'floatX'

**Comment by pbashivan** [comment]
I see. It's weird that having the same package versions you are still getting this error. Try setting this ENV variable when running the script. 

```
THEANO_FLAGS='floatX=float32' python <script_name.py>
```

**Comment by Ibrainscn** [comment]
Finally, it works now! Thanks so much!!

For the topology-preserving projections of electrode locations (3D-->2D), I am just wondering the input for the following function is in 3D Cartesian Coordinates (x, y, z), right? That means your sample data Neuroscan_locs_orig.mat is a Neuroscan 64 EEG channels system in Cartesian Coordinates (x, y, z), right?

def azim_proj(position):
    """
    Computes the Azimuthal Equidistant Projection of input point in 3D Cartesian Coordinates.

If I change the input "position" by using let's say Biosemi (another EEG system) 128 channel location files in Cartesian Coordinates. It should also work, right? 

Thanks for your help and clarification.

**Comment by pbashivan** [comment]
Yes, the inputs are in Cartesian coordinates. It should work if you replace the channel coordinates with another one of your choice (in Cartesian coordinates).

**Comment by Ibrainscn** [comment]
I see. Thanks so much. Really appreciate your help.
