### ISSUE TITLE
Which electrode corresponds to the three-dimensional coordinates

### ISSUE THREAD

**Issue by sdnuzwk** [pouya-bashivan/EEGLearn#39]
Dear Professor, is the 64-lead electrode mentioned in the text agreed upon in quik-cap?
The three-dimensional coordinates in the coordinate file of the electrode in the project, which electrode corresponds to which?
Please help me solve the problem at a convenient time.

**Comment by sdnuzwk** [comment]
Dear Professor，I am in urgent need

**Comment by pbashivan** [comment]
Unfortunately I don't have the channel names for the coordinates anymore. But one thing you can do is to make a 3d plot of electrode locations and compare it to the electrode map for quik-cap like this one: 
[https://compumedicsneuroscan.com/product/64-channels-quik-cap/](url)

**Comment by sdnuzwk** [comment]
@pbashivan Thank you very much, your idea is very effective.
