### ISSUE TITLE
Hi, I reimplemented EEGLearn with tensorflow, and made it public

### ISSUE THREAD

**Issue by YangWangsky** [pouya-bashivan/EEGLearn#40]
Dear author,

EEGLearn is really nice work. However, theano is no longer updated, I reimplemented EEGLearn with tensorflow, and publicly posted it on my GitHub (https://github.com/YangWangsky/tf_EEGLearn).  
         
I think this may make more people benefit from EEGLearn.  I would appreciate it if you can put my implementation in your README.md.

**Comment by pbashivan** [comment]
Thanks @YangWangsky 
I will update the readme.
