### ISSUE TITLE
Extracting psd features

### ISSUE THREAD

**Issue by michaelmart77** [pouya-bashivan/EEGLearn#41]
Hi,
I have epoched data from EEGLAB. Every epoch has 250 time frames. I'm still not able to extract the frequency features to be as mentioned in your example. The data should be:
(number of samples, number of electrodes * number of frequency bands * number of time windows).
I'm trying in MNE-Python to do this but no way. As a result I'm getting (number of samples , number of electrodes * number of frequency bands). So I'm not able to divide each epoch to windows as it should be. Could you kindly tell me which function do you use. either in EEGLAB or in MNE?
To extract the frequency features, I'm using this code in MNE-Python after getting epoched data from EEGLAB:

def eeg_power_band(epochs):
   FREQ_BANDS = {"theta": [4.5, 8.5], "alpha": [8.5, 11.5], "beta": [15.5, 30]}
   epochs = epochs.load_data().pick_channels(EEG_CHANNELS).get_data()
   psds, freqs = mne.time_frequency.psd_welch(epochs, fmin=0.5, fmax=30.,n_fft=250, n_overlap=0)
    # Normalize the PSDs
    psds /= np.sum(psds, axis=-1, keepdims=True)
    X = []
    for _, (fmin, fmax) in FREQ_BANDS.items():
        psds_band = psds[:, :, (freqs >= fmin) & (freqs < fmax)].mean(axis=-1)
        #X.append(psds_band.reshape(len(psds), -1))
        X.append(psds_band)
    return np.concatenate(X, axis=1)

Many many thanks in advance

**Comment by pbashivan** [comment]
From py-MNE docs, get_data() returns  array of shape (n_epochs, n_channels, n_times). 
You can subselect a time window by simply selecting different indices in the last axis. 
data[..., 0:100]

You should ask this question on stackoverflow or py-MNE forum.
