### ISSUE TITLE
Parameters and configuration of the modified version of the Sternberg memory task.

### ISSUE THREAD

**Issue by JessicaLR** [pouya-bashivan/EEGLearn#42]
I have a question about the size of the letters in the modified experiment of the memory task of Sternberg that you adopted in your data set, mentions that the size should be 1.15 °. However I do not understand the reference in terms of degrees refers or what kind of measure is, more still defines a visual angle of 2.9 ° this in terms of the issue of location and spacing between characters or with respect to what situation is established measure. Thank you for your attention, I am waiting for your response.

**Comment by JessicaLR** [comment]
I'm trying to replicate the experiment that you have done for memory task. Thanks!

**Comment by pbashivan** [comment]
If I understand correctly, you're asking about how the visual angle is calculated. You can refer to this link: 

https://en.wikipedia.org/wiki/Visual_angle

**Comment by JessicaLR** [comment]
thank you very much! Another question that I have is what measure is 1.15°, what do you mean with °? Degrees? How can you convert to other measure?

**Comment by pbashivan** [comment]
Yes, it means degrees. You can google how to convert degrees to other units like radians
