### ISSUE TITLE
Save Predictions

### ISSUE THREAD

**Issue by GulrukhTurabee** [pouya-bashivan/EEGLearn#43]
Hello pbashivan @p

I am trying to save predictions ( predicted values and true values) either as .mat file or .npy file. however, i can't find on the internet how can i saved in theano/lasagne? can you help me with that?

Thank You

**Comment by pbashivan** [comment]
You need to define a theano function (theano.function) and retrieve the predictions for a specific layer see [here](https://github.com/pbashivan/EEGLearn/blob/master/eeglearn/eeg_cnn_lib.py#L387). You can then get the predictions by running the theano function similar to [this](https://github.com/pbashivan/EEGLearn/blob/master/eeglearn/eeg_cnn_lib.py#L418).

**Comment by GulrukhTurabee** [comment]
Can you provide an example please?

**Comment by GulrukhTurabee** [comment]
Hi @pbashivan

I have implemented the following lines of code and according to me it should give correct results, however, it is not. Can you check what is wrong?   

test_prediction = lasagne.layers.get_output(network, deterministic=True)
    result = T.argmax(test_prediction, axis=1)
    predict_function = theano.function([input_var],result)
    pred= predict_function(X_test)
 
    with open("predict_label.txt","w") as text_file:
     print(pred, file = text_file)
    with open("groundtruth_label.txt","w") as text_file:
     print(y_test, file = text_file)

    print("Saving result ...")
    out_predict = open('predict.pkl', 'wb')
    pickle.dump(pred, out_predict)
    
    thefile = open('predict.txt','w')
    for item in pred:
        thefile.write('%s\n' % item)

    out_groundtruth = open('groundtruth.pkl', 'wb')
    pickle.dump(y_test, out_groundtruth)

Thankyou

**Comment by pbashivan** [comment]
Do you get an error when running this?

**Comment by GulrukhTurabee** [comment]
Hi @pbashivan 
No it is working now thanks though. I am now trying to save activations for first CNN layer. Do you have any idea how can it be done?

Thanks
