### ISSUE TITLE
the sample data  structure

### ISSUE THREAD

**Issue by wangqinxuan** [pouya-bashivan/EEGLearn#45]
the FeatureMat_timeWin.mat in your sample dataset have a ndarray and shape= (2760,1344),so,what is 1344? And where is the 64 electrodes channels signal ?

**Comment by javadbayazi** [comment]
I think the readme.tex would help you.

"FeatureMat_timeWin:
FFT power values extracted for three frequency bands (theta, alpha, beta). Features are arranged in band and electrodes order (theta_1, theta_2..., theta_64, alpha_1, alpha_2, ..., beta_64). There are seven time windows, features for each time window are aggregated sequentially (i.e. 0:191 --> time window 1, 192:383 --> time windw 2 and so on. Last column contains the class labels (load levels)."

**Comment by pbashivan** [comment]
As @MohammadJavadD suggested please refer to the readme file

 [https://github.com/pbashivan/EEGLearn/blob/master/Sample%20data/README.txt](url)

**Comment by wangqinxuan** [comment]
&nbsp;&nbsp;&nbsp;&nbsp; Thanks for your reply.
 &nbsp;&nbsp;&nbsp;&nbsp; In fact ,general eeg data format shape=(samples,Number of electrodes,each electrodes data). And I have a dataset shape=(287,64,3000),nb_class=2. so,I must process the dataset if I want to use your code to train my dataset.But I don't know how to process it.Therefore, it's&nbsp;great to support your data processing codes.
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Mohammad Javad Darvishi"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月30日(星期六) 凌晨2:45
 收件人:&nbsp;"pbashivan/EEGLearn"<EEGLearn@noreply.github.com&gt;;
 抄送:&nbsp;"王沁轩"<1124841489@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [pbashivan/EEGLearn] the sample data structure (#45)

 

 
I think the readme.tex would help you.
 
"FeatureMat_timeWin:
FFT power values extracted for three frequency bands (theta, alpha, beta). Features are arranged in band and electrodes order (theta_1, theta_2..., theta_64, alpha_1, alpha_2, ..., beta_64). There are seven time windows, features for each time window are aggregated sequentially (i.e. 0:191 --&gt; time window 1, 192:383 --&gt; time windw 2 and so on. Last column contains the class labels (load levels)."

**Comment by wangqinxuan** [comment]
> As @MohammadJavadD suggested please refer to the readme file
> 
> [https://github.com/pbashivan/EEGLearn/blob/master/Sample%20data/README.txt](url)
it's better to support the codes of the  'FeatureMat_timeWin.mat' produce process.
