### ISSUE TITLE
Can this be updated to Python >= 3.7

### ISSUE THREAD

**Issue by dans-acc** [pouya-bashivan/EEGLearn#46]
Hello,

I was wondering whether this repository could be updated for Python >= 3.7? I feel as though this would be appropriate.

Best,

Dans.

**Comment by pbashivan** [comment]
I made some minor changes to the image-transformation code to make it compatible with python 3.x. I no longer support the neural network training code. I suggest you use the reimplementations in Tensorflow or PyTorch (links in the readme).
