### ISSUE TITLE
The function azim_proj(pos)

### ISSUE THREAD

**Issue by zwj1996-xjt** [pouya-bashivan/EEGLearn#49]
Dear professor:
Thanks for your algorithms. 
In the function :
 [r, elev, az] = cart2sph(pos[0], pos[1], pos[2])
 return pol2cart(az, m.pi / 2 - elev)
I don't understand the second actual parameter  m.pi / 2 - elev,  I think maybe it should equal to r*(m.pi/2-elev).
Could you please help me understand why there is no r?

**Comment by pbashivan** [comment]
I think the original transformation comes with an assumption that the points are positioned on a unit sphere. If the assumption is not correct (which I assume it could easily happen in the case of EEG electrode locations on the scalp) then we should probably correct it by multiplying the elevation distance (m.pi/2 - elev) with a coefficient dependent on the "r".
However it would not simply be "r" - it probably needs to be some measure of deviation from the sphere assumption. 

My guess is that you could normalize the r-values across all locations and then use the normalized values as coefficients as you suggested.
