### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by wangyue663** [pouya-bashivan/EEGLearn#50]
@BashivanLab  Dear professor, I still have a few questions:
1. When generating the data set, does the order of the three-dimensional coordinates of the electrode correspond to the coordinate index of each frequency band in Neuroscan_locs_orig?
2. I extract the power spectrum of each frequency band to find the average power, then follow the method in step 1 to generate a data set, and finally generate an image. Does the white area in the image mean that all three frequency bands are active? Does more color area in which frequency band mean that the frequency band is more active?
3. https://github.com/wangyue663/images/blob/main/E%24NI8C%7DGFD(NF%4036OSP0%7D2N.png
This is the picture I generated, basically every picture has a black part， Is this normal?
thank you very much!

**Comment by wangyue663** [comment]
Sorry to disturb you.

**Comment by wangyue663** [comment]
@BashivanLab  I'm sorry to disturb you many times, I won't disturb you again next time, I'm so sorry.

**Comment by fangtao365** [comment]
@wangyue663 hello,i have same problems,can you add my wechat:19821234051?
