### ISSUE TITLE
Undefined reduct() function

### ISSUE THREAD

**Issue by Slasnista** [pouya-bashivan/EEGLearn#7]
Hi,
What is the function reduce() used at sign 473 ?  https://github.com/pbashivan/EEGLearn/blob/master/eeglearn/eeg_cnn_lib.py#L473

It is not defined in the utils and I cannot make the code run.

Thanks a lot !

**Comment by pbashivan** [comment]
Hi @Slasnista 
It's the python 2.7 built-in function reduce. 
https://docs.python.org/2/library/functions.html#reduce

It could be replaced with functools.reduce or `for` loop to be compatible with python 3.x 
I'll fix it sometime this week.

**Comment by Slasnista** [comment]
Ok thank you for the fast answer !

**Comment by pbashivan** [comment]
Fixed
f729444aee6aee245f439fa2fe66431581168e75
