### ISSUE TITLE
downsample issue

### ISSUE THREAD

**Issue by ShibaPrasad** [pouya-bashivan/EEGLearn#8]
Hi pbashivan,

I am getting below error. I thinking i have installed everything correct. Please help  on this and struct

Using gpu device 0: Tesla K40c (CNMeM is disabled, cuDNN 5110)
Traceback (most recent call last):
  File "/home/shiba/Desktop/Note/EEGLearn-master/eeglearn/eeg_cnn_lib.py", line 17, in <module>
    import lasagne
  File "/home/shiba/anaconda2/lib/python2.7/site-packages/lasagne/__init__.py", line 24, in <module>
    from . import layers
  File "/home/shiba/anaconda2/lib/python2.7/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/home/shiba/anaconda2/lib/python2.7/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample

**Comment by ShibaPrasad** [comment]
resolved the issue. 
i would like to extend it into LSTN network ....please give me some suggestions.

**Comment by pbashivan** [comment]
Are you getting an error when running the LSTM?

**Comment by ShibaPrasad** [comment]
I am able to run the program. 
I am referring your code and trying to enhance (Please recommend me if anything). Basically i am concentrating on ML side and no EEG data available with me. Would you suggest any dataset so that I will refer for my work.

Would it be possible to ask few question:
On sample data directory you have provided below files
FeatureMat_timeWin.mat	
Neuroscan_locs_orig.mat		
trials_subNums.mat

Are these 3 files needed for your whole paper implementation.

**Comment by pbashivan** [comment]
They contain the extracted EEG features, electrode 3D locations, and subject numbers.

Here is a description of what those files contain:
https://github.com/pbashivan/EEGLearn/blob/master/Sample%20data/README.txt

**Comment by pbashivan** [comment]
I'm closing this, feel free to reopen if any issues remain.

**Comment by ShibaPrasad** [comment]
Thanks. But i would like to know how the below files formed (As i am trying with other datasets) 
FeatureMat_timeWin.mat
Neuroscan_locs_orig.mat
trials_subNums.mat
