### ISSUE TITLE
can you please upload training code for sample data?

### ISSUE THREAD

**Issue by anindyasarkarIITH** [pouya-bashivan/EEGLearn#9]
do you have the training code?
I tried the following code:

import eeglearn
import eeglearn.eeg_cnn_lib as eeglib
import scipy.io as sio
locs = sio.loadmat('/home/anindya/Projects/EEGLearn-master/Sample data/Neuroscan_locs_orig.mat')
locs_a = locs['A']
features = sio.loadmat('/home/anindya/Projects/EEGLearn-master/Sample data/FeatureMat_timeWin.mat')
features_a = features['features']
images = eeglib.gen_images(locs_a, features_a, 1024)

but it is giving the assertion error in gen_images function

**Comment by pbashivan** [comment]
Have you looked at this:
https://github.com/pbashivan/EEGLearn/blob/master/eeglearn/eeg_cnn_lib.py#L446

**Comment by anindyasarkarIITH** [comment]
thanks..it's working..
